config/routes.rb
Gigsurfing::Application.routes.draw do
  resources :activities, only: [:index]

  get 'tags/:tag', to: 'homepage#index', as: :genres
  resources :bands
  resources :statuses
  resources :instruments

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end
  
  root "homepage#index"

  as :user do
    get "/register", :to => "devise/registrations#new", :as => :register
    get "/login", :to => "devise/sessions#new", :as => :login
    get "/logout", :to => "devise/sessions#destroy", :as => :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end
  
  get '/:id', to: 'profiles#show', as: 'profile'
  

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  before_action :find_user
  respond_to :html, :json

  def index
    # if params[:tag]
    #   @bands = Band.tagged_with(params[:tag])
    #   @statuses = Status.tagged_with(params[:tag])
    # else
    #   @bands = Band.order('created_at desc').all
    #   @statuses = Status.order('created_at desc').all
    # end
    params[:page] ||= 1
    @activities = Activity.for_user(current_user, params)
    respond_with @activities

  end

  private

  def find_user
    if user_signed_in?
      @user = current_user || User.find_by_profile_name(params[:id]) 
      if @user
        @bands = @user.bands.all
        render action: :index
      else
        render file: 'public/404', status: 404, formats: [:html]
      end
    end
  end

end

app/views/homepage/_call_to_action.html.haml
%body#homepage
  .travel
    %h3 See the world with your bandmates
  .middle
    %h3 or
  .help
    %h3 Support great world musicians
  .call-button
    = link_to "Sign Up!", new_user_registration_path, class: 'btn btn-custom'
    %br 
    = link_to "Login!", new_user_session_path, class: 'btn btn-custom'

app/views/homepage/_landing.html.haml
.profile-pic
  = avatar_profile_link @user, {}, class: 'pull-left'

= link_to "Add your Band", new_band_path, class: "btn btn-default"
= link_to "New Status", new_status_path, class: "btn btn-default"
= link_to "New Instrument", new_instrument_path, class: "btn btn-default"

#tag_cloud
  - tag_cloud Band.tag_counts, %w[s m l] do |tag, css_class|
    = link_to tag.name, genres_path(tag.name), class: css_class

%h1 Activity Feed
- current_user.activities.each do |activity|
  -if activity.targetable
    .media
      = avatar_profile_link activity.user(:thumb), {}, class: 'pull-left'
      = link_to image_tag(activity.user.gravatar_url), profile_path(activity.user)
      .media-body
        %h4.media-heading 
          = activity.user.name_display
        = render partial: "activities/#{activity.targetable_type.underscore}/#{activity.action}", locals: { activity: activity }                                                          
        %br
    %hr
/ = will_paginate current_user.activities
/ - if @bands
/   %h2 Bands:
/   - @bands.each do |band|
/     - if can_display_band(band)    
/       %h3= link_to "#{band.name}", band_path(band)
/       - if band.document && band.document.attachment?
/         = band_logo_display(band)
/       %br
/       Genres:
/       = raw band.tag_list.map { |t| link_to t, genres_path(t) }.join(', ')
/       %br
/       %p Band Members:
/       - band.users.each do |member|
/         = link_to "#{member.name_display}", profile_path(member)

/       %p= link_to "Edit", edit_band_path(band)
/       / %p= link_to "Band Owner: #{band.user.name_display}", profile_path(band.user)- if @bands

/ - @statuses.each do |status|
/   %h2 Statuses:
/   - if can_display_status(status)    
/     %h3= link_to "#{status.content}", status_path(status)
/     - if status.document && status.document.attachment?
/       = status_document_link(status)
/     %br
/     %p= link_to "Edit", edit_status_path(status)
/     %p= link_to "Delete", status_path(status), method: :delete, data: { confirm: "Are you sure?"}

app/views/homepage/index.html.haml
- if user_signed_in?
  = render "landing"
- else
  = render 'call_to_action'