config/routes.rb
Gigsurfing::Application.routes.draw do
  resources :activities, only: [:index]

  get 'tags/:tag', to: 'homepage#index', as: :genres
  resources :bands
  resources :statuses
  resources :instruments

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end
  
  root "homepage#index"

  as :user do
    get "/register", :to => "devise/registrations#new", :as => :register
    get "/login", :to => "devise/sessions#new", :as => :login
    get "/logout", :to => "devise/sessions#destroy", :as => :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end
  
  get '/:id', to: 'profiles#show', as: 'profile'
  

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  # before_action :find_status, except: [:index, :new, :create]

  def index
    @statuses = Status.order('created_at desc').all

    respond_to do |format|
      format.html 
      format.json { render json: @statuses }
    end
  end

  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html 
      format.json { render json: @status }
    end
  end

  def new
    @status = current_user.statuses.new
    @status.build_document

    respond_to do |format|
      format.html 
      format.json { render json: @status }
    end
  end

  def edit
    @status = current_user.statuses.find(params[:id])
  end


  def create
    @status = current_user.statuses.new status_params

    respond_to do |format|
      if @status.save
        current_user.create_activity(@status, 'created')
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @status = current_user.statuses.find(params[:id])
    @document = @status.document

    @status.transaction do
      @status.update_attributes status_params
      @document.update_attributes(document_params) if @document
      current_user.create_activity(@status, 'updated')
      unless @status.valid? || (@status.valid? && @document && !@document.valid?)
        raise ActiveRecord::Rollback
      end
    end
    
    respond_to do |format|
      format.html { redirect_to @status, notice: 'Status was successfully updated.' }
      format.json { head :no_content }
    end
  rescue ActiveRecord::Rollback
    respond_to do |format|
      format.html do
        flash.now[:error] = "Update failed."
        render action: "edit"
      end
      format.json { render json: @status.errors, status: :unprocessable_entity }
    end
  end

  def destroy
    @status = current_user.statuses.find(params[:id])
    @status.destroy
    # current_user.create_activity(@status, 'deleted')

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private

  def document_params
    params.permit([:attachment, :remove_attachment])
  end

  def status_params
    params.require(:status).permit([:content, {document_attributes: [:attachment, :remove_attachment]}])
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.haml
= simple_form_for(@status, html: {class: "form-horizontal", multipart: true}) do |f|
  - if @status.errors.any?
    #error_explanation
      %h2
        = pluralize(@status.errors.count, "error")
        prohibited this status from being saved:
      %ul
        - @status.errors.full_messages.each do |msg|
          %li= msg
  = f.input :content, input_html: { rows: 4, class: 'input-xxlarge' }
  = f.fields_for :document do |document_fields|
    - if document_fields.object.attachment?
      .control-group
        %label.control-label Current attachment
        .controls
          = link_to document_fields.object.attachment_file_name, document_fields.object.attachment.url
      = document_fields.input :remove_attachment, as: :boolean, label: "Remove attachment?"
    = document_fields.input :attachment, as: :file
  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to "Back", statuses_path, class: 'btn'

app/views/statuses/edit.html.haml
= page_header do
  %h1 Edit Status Update

= render 'form'

app/views/statuses/index.html.haml
%h1 All Statuses:
- @statuses.each do |status|
  = status.content
  - if status.document && status.document.attachment?
    = status_document_link status
    %hr

app/views/statuses/new.html.haml
= page_header do
  %h1 New Status Update

= render 'form'

app/views/statuses/show.html.haml
.row
  .span8.offset2
    = page_header do
      %h1
        = avatar_profile_link @status.user
        = @status.user.name_display
        %small= time_ago_in_words(@status.created_at) + " ago"
    %p
      = @status.content
    %hr/
    - if @status.document && @status.document.attachment?
      = status_document_link @status
      %hr/
    .meta
      = link_to 'Back', statuses_path
      - if signed_in? && @status.user == current_user
        |
        \#{link_to "Edit", edit_status_path(@status)} |
        \#{link_to "Delete", @status, method: :delete, data: { confirm: "Are you sure your want to delete this status?"}}