config/routes.rb
Gigsurfing::Application.routes.draw do
  resources :activities, only: [:index]

  get 'tags/:tag', to: 'homepage#index', as: :genres
  resources :bands
  resources :statuses
  resources :instruments

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end
  
  root "homepage#index"

  as :user do
    get "/register", :to => "devise/registrations#new", :as => :register
    get "/login", :to => "devise/sessions#new", :as => :login
    get "/logout", :to => "devise/sessions#destroy", :as => :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end
  
  get '/:id', to: 'profiles#show', as: 'profile'
  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :album
  belongs_to :user
  has_attached_file :asset, :styles => { :medium => "300x300>", :thumb => "100x100>", :large => "600x600>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/

  def to_s
    caption? ? caption : "Picture"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :update, :edit, :destroy]
  before_action :find_user
  before_action :find_album
  before_action :find_picture, only: [:edit, :update, :show, :destroy]
  # before_action :ensure_proper_user, only: [:edit, :new, :create, :update, :destroy]
  before_action :add_breadcrumbs

  def index
    @pictures = @album.pictures.all

    respond_to do |format|
      format.html
      format.json { render json: @pictures }
    end
  end

  def show
    # add_breadcrumb @picture.caption
    add_breadcrumb @picture, album_picture_path(@album, @picture)
    respond_to  do |format|
      format.html
      format.json { render json: @picture}
    end
  end 

  def new
    @picture = @album.pictures.new
    respond_to  do |format|
      format.html
      format.json { render json: @picture}
    end
  end

  def create
    @picture = @album.pictures.new picture_params
    @picture.user = current_user
    respond_to do |format|
      if @picture.save
        current_user.create_activity(@picture, 'created')
        format.html { redirect_to album_pictures_path(@album), notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @picture.update_attributes picture_params
        current_user.create_activity(@picture, 'updated')
        format.html { redirect_to album_pictures_path(@album), notice: "Picture was successfully updated."}
        format.json { head :no_content}
      else
        format.html { render action: "edit"}
        format.json { render json: @picture.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to album_pictures_path(@album) }
      format.json { head :no_content }
    end
  end

  #overwrite ApplicationController url_options
  def url_options
    { profile_name: params[:profile_name] }.merge(super)
  end

  private

  # def ensure_proper_user
  #   if current_user.profile_name != @user
  #     flash[:error] = "You don't have permission to do that"
  #     redirect to album_pictures_path
  #   end
  # end

  def add_breadcrumbs
    add_breadcrumb @user.first_name, profile_path(@user)
    add_breadcrumb 'Albums', albums_path
    add_breadcrumb 'Pictures', album_pictures_path(@album)
  end

  def find_user
    @user = User.find_by_profile_name(params[:profile_name])
  end

  def find_album
    if signed_in? && current_user.profile_name == params[:profile_name]
      @album = current_user.albums.find(params[:album_id])
    else
      @album = @user.albums.find(params[:album_id])
    end
  end

  def find_picture
    @picture = @album.pictures.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit([:caption, :description, :asset])
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def can_edit_picture?(picture)
    signed_in? && current_user == picture.user
  end
end

app/views/pictures/_form.html.haml
= simple_form_for([@album, @picture], html: { class: 'form-horizontal' }) do |f|
  = f.error_notification
  .form-inputs
    = f.input :asset, as: :file
    = bootstrap_paperclip_picture f, :asset
    = f.input :caption
    = f.input :description, input_html: { class: 'input-xxlarge', rows: 4 }
  .form-actions
    = f.button :submit

app/views/pictures/edit.html.haml
%h1 Edit Picture
= render "form"
= link_to "Show", album_picture_path(@album, @picture)
= link_to "Back", album_pictures_path(@album)

app/views/pictures/index.html.haml
- if signed_in? && current_user === @user
  = link_to "Add Picture", new_album_picture_path(current_user, @album), class: "btn btn-default"
%h1=@album.title
%ul.thumbnails
  - @pictures.each do |picture|
    .col-md-3
      %li.thumbnail
        =link_to image_tag(picture.asset.url(:thumb)), album_picture_path(@user, @album, picture)
        %br
        .caption
          - if picture.caption?
            = picture.caption
        %br
        = link_to "View Full Size", album_picture_path(@user, @album, picture)
        - if can_edit_picture?(picture)
          = link_to "Edit", edit_album_picture_path(@album, picture)
          = link_to "Delete", album_picture_path(@album, picture), method: :delete, data: { confirm: "Are you sure?"}

app/views/pictures/new.html.haml
%h1 New Picture
= render "form"

= link_to "Back", album_pictures_path(@album)

app/views/pictures/show.html.haml
%h1 Viewing Picture

= image_tag(@picture.asset.url(:large))
%br
%h3= @picture.caption
%p= @picture.description

= link_to "Edit", edit_album_picture_path(@album, @picture)
= link_to "Album", album_pictures_path(@album)