config/routes.rb
Gigsurfing::Application.routes.draw do
  resources :activities, only: [:index]

  get 'tags/:tag', to: 'homepage#index', as: :genres
  resources :bands
  resources :statuses
  resources :instruments

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end
  
  root "homepage#index"

  as :user do
    get "/register", :to => "devise/registrations#new", :as => :register
    get "/login", :to => "devise/sessions#new", :as => :login
    get "/logout", :to => "devise/sessions#destroy", :as => :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end
  
  get '/:id', to: 'profiles#show', as: 'profile'
  

end

app/models/instrument.rb
class Instrument < ActiveRecord::Base

  has_one :category
  has_one :subcategory

  belongs_to :user
  belongs_to :document

  accepts_nested_attributes_for :document
  
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :find_instrument, except: [:index, :new, :create]

  def index
    @instruments = Instrument.all
  end

  def new
    @instrument = current_user.instruments.new
    @instrument.build_document
    respond_to  do |format|
      format.html
      format.json { render json: @instrument}
    end
  end

  def create
    @instrument = current_user.instruments.new instrument_params
    @instrument.build_document
    if @instrument.save 
      current_user.create_activity(@instrument, 'created')
      redirect_to root_url, notice: "Band added!"
    else
      render :new
    end
  end

  def edit
    @instrument.build_document
  end

  def update
    @document = @instrument.document

    @instrument.transaction do
      @instrument.update_attributes(instrument_params)
      @document.update_attributes(document_params) if @document
      current_user.create_activity(@instrument, 'updated')
      unless @instrument.valid? || (@instrument.valid? && @document && !@document.valid?)      
        raise ActiveRecord::Rollback 
      end
    end
    
    respond_to do |format|    
      format.html {redirect_to @instrument, notice: "Gear was updated successfully."}
      format.json { head :no_content }
    end

    rescue ActiveRecord::Rollback
      respond_to do |format|
        format.html do
          flash.now[:error] = "Update failed."
          render :edit 
        end
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
  end

  def show

  end

  private

  def find_instrument
    @instrument = Instrument.find(params[:id])
  end

  def document_params
    params.permit([:attachment, :remove_attachment])
  end

  def instrument_params
    params.require(:instrument).permit(:name, :description, :category, :subcategory, {document_attributes: [:attachment, :remove_attachment]}, :user_id, :document_id)
  end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/instruments/_form.html.haml
= form_for @instrument, html: { :multipart => true } do |f|  
  .col-md-6
    Name:
    %br
    .col-md-12
      = f.text_field :name, class: "form-control"
    Description:
    %br
    .col-md-12
      = f.text_area :description, class: "form-control"
    %br
    .col-md-12
      = f.label :category_id
      = f.collection_select :category_id, Category.order(:name), :id, :name, include_blank: true
    %br
    .col-md-12
      = f.label :subcategory_id
      = f.grouped_collection_select :subcategory_id, Category.order(:name), :subcategories, :name, :id, :name, include_blank: true
    %br
    <strong>Picture</strong>
    = f.fields_for :document do |document_fields|
      - if document_fields.object.attachment?
        .control-group
          %label.control-label Current attachment
          .controls
            = link_to document_fields.object.attachment_file_name, document_fields.object.attachment.url
      = document_fields.check_box :remove_attachment, as: :boolean, label: "Remove attachment?"
      = document_fields.file_field :attachment
    %br
    %br
    = f.submit value: 'Add', class: 'btn btn-default'

app/views/instruments/edit.html.haml
%h1 Edit youe gear
= render 'form'

app/views/instruments/index.html.haml
%h1 Your Gear
- @instruments.each do |instrument|
  = instrument.name
  = instrument.description
  - if instrument.document && instrument.document.attachment?
    = gear_image_display(instrument)  
  = link_to "Edit", edit_instrument_path(instrument)

app/views/instruments/new.html.haml
%h1 Add a New Piece of Gear

= render 'form'

app/views/instruments/show.html.haml
%h3= @instrument.name

- if @instrument.document && @instrument.document.attachment?
  = gear_image_display(@instrument)